name: Update Example Dependency

on:
  schedule:
    - cron: "0 0 * * 0" # Runs weekly at midnight on Sunday
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  updateExampleDependency:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install jq
        run: sudo apt-get install jq -y
      - name: Get Latest Example Dependency Version
        id: get-latest-version
        run: |
          # Fetch the latest release version of the dependency
          LATEST_VERSION=$(curl -sL https://api.github.com/repos/mlpack/mlpack/releases/latest | jq -r ".tag_name" | tr -d 'v')
          echo "latest_version=$LATEST_VERSION" >> $GITHUB_OUTPUT

          # Extract current version from the project file (adjust the path and command as needed)
          CURRENT_VERSION=$(grep -oP '(?<=example-dependency": ")[^"]*' path/to/dependency/file)
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT

      - name: Update Example Dependency
        if: steps.get-latest-version.outputs.latest_version != steps.get-latest-version.outputs.current_version
        run: |
          # Update the dependency version in your project file
          sed -i "s/$CURRENT_VERSION/$LATEST_VERSION/g" path/to/dependency/file
          
          # Optionally, you can add other update steps here, like updating lock files or running tests

      - name: Create Pull Request
        if: steps.get-latest-version.outputs.latest_version != steps.get-latest-version.outputs.current_version
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "Update example-dependency to version ${{ steps.get-latest-version.outputs.latest_version }}"
          title: "Update example-dependency to version ${{ steps.get-latest-version.outputs.latest_version }}"
          body: |
            This PR updates example-dependency to version ${{ steps.get-latest-version.outputs.latest_version }}.
            Auto-generated by GitHub Actions.
          branch: update-example-dependency-${{ steps.get-latest-version.outputs.latest_version }}
          labels: automated update, dependencies
